---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, e-series' 
summary: Erfahren Sie, was es Neues bei der Verwaltung von E-Series-Systemen in BlueXP gibt. 
---
= Was ist neu beim E-Series-Management?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informieren Sie sich über die Neuerungen bei der Verwaltung von E-Series-Systemen in der NetApp Console.



== 06. Oktober 2025



=== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp -Speicher und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Arbeitsabläufe und eine vereinfachte Verwaltung mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen finden Sie imlink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Versionshinweise zur NetApp Console"] .



== 12. Mai 2025



=== BlueXP -Zugriffsrolle erforderlich

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um E-Series in BlueXP anzuzeigen, zu entdecken oder zu verwalten: Organisationsadministrator, Ordner- oder Projektadministrator, Speicheradministrator oder Systemintegritätsspezialist.  https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP -Zugriffsrollen."^]



== 18. September 2022



=== Support für die E-Serie

Sie können Ihre E-Serie-Systeme jetzt direkt von BlueXP aus entdecken.  Durch die Erkennung von E-Series-Systemen erhalten Sie einen vollständigen Überblick über die Daten in Ihrer gesamten Hybrid-Multicloud.
